{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pymongo in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages\\pymongo-4.6.3-py3.9-win-amd64.egg (4.6.3)\n",
      "Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages\\dnspython-2.6.1-py3.9.egg (from pymongo) (2.6.1)\n",
      "Pinged successfully!. You are connected to Mongodb.\n"
     ]
    }
   ],
   "source": [
    "! pip install pymongo\n",
    "\n",
    "from pymongo.mongo_client import MongoClient\n",
    "\n",
    "\n",
    "uri=\"mongodb+srv://merchant0710:VWzhQ6hxUTvxhQsg@creditdata.cafakii.mongodb.net/\"\n",
    "client=MongoClient(uri)\n",
    "\n",
    "try:  \n",
    "    client.admin.command('ping')\n",
    "    print(\"Pinged successfully!. You are connected to Mongodb.\")\n",
    "\n",
    "except Exception as e:\n",
    "    raise(e)\n",
    "\n",
    "db=client.test\n",
    "db=client['DATABASE']\n",
    "collection_sensor=db['CreditCardFaultDetection']"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages\\pandas-2.0.3-py3.9-win-amd64.egg (2.0.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages (from pandas) (2.9.0)\n",
      "Requirement already satisfied: pytz>=2020.1 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages\\pytz-2024.1-py3.9.egg (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.1 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages\\tzdata-2024.1-py3.9.egg (from pandas) (2024.1)\n",
      "Requirement already satisfied: numpy>=1.20.3 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages (from pandas) (1.26.4)\n",
      "Requirement already satisfied: six>=1.5 in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)\n",
      "^C\n",
      "Requirement already satisfied: numpy in d:\\datascience\\mlprojects\\creditcardfaultdetetction\\env\\lib\\site-packages (1.26.4)\n"
     ]
    }
   ],
   "source": [
    "! pip install pandas\n",
    "! pip uninstall numpy\n",
    "\n",
    "! pip install numpy\n",
    "\n",
    "import pandas as pd\n",
    "\n",
    "\n",
    "data=pd.read_csv(r'D:\\DataScience\\MLProjects\\CreditCardFaultDetetction\\notebooks\\CreditCardData')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "DONE!\n"
     ]
    }
   ],
   "source": [
    "data_dict=data.to_dict(orient='records')\n",
    "\n",
    "collection_sensor.insert_many(data_dict)\n",
    "\n",
    "print(\"DONE!\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
